codecov:
  notify:
    after_n_builds: 15

coverage:
  status:
    patch:
      default:
        target: 100%
        informational: true # Once the project achieves high code coverage, consider making it a mandatory check.
    project:
      default:
        target: auto
