# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04 # renovate: datasource=docker depName=ubuntu versioning=ubuntu
  tools:
    python: '3.13' # renovate: datasource=python-version depName=python
    # TODO: Remove rust once Pendulum provides wheels for Python 3.13. https://github.com/python-pendulum/pendulum/issues/844
    rust: latest

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: requirements/docs.txt
   - method: pip
     path: .
