from tests import FlexGetBase
import os
import os.path
from tests.util import maketemp

class TestExistsSeries(FlexGetBase):

    __yaml__ = """
        feeds:
          test:
            input_mock:
              - {title: 'Foo.Bar.S01E02.XViD-FlexGet'}
              - {title: 'Foo.Bar.S01E03.XViD-FlexGet'}
            series:
              - foo bar
            exists_series: path autogenerated in setup()
            
          test_diff_qualities:
            input_mock:
              - {title: 'Asdf.S01E02.720p-FlexGet'}
            series:
              - asdf
            exists_series: path autogenerated in setup()
    """

    test_dirs = ['Foo.Bar.S01E02.XViD.FlexGet', 'Asdf.S01E02.HDTV-FlexGet']
    
    def __init__(self):
        self.test_home = None
        FlexGetBase.__init__(self)

    def setup(self):
        FlexGetBase.setup(self)
        self.test_home = maketemp()
        for feed_name in ['test', 'test_diff_qualities']:
            self.manager.config['feeds'][feed_name]['exists_series'] = self.test_home
        for dir in self.test_dirs:
            os.mkdir(os.path.join(self.test_home, dir))
        
    def teardown(self):
        # remove test dirs
        for dir in self.test_dirs:
            os.rmdir(os.path.join(self.test_home, dir))
        os.rmdir(self.test_home)
        FlexGetBase.teardown(self)

    def test_existing(self):
        self.execute_feed('test')
        assert not self.feed.find_entry('accepted', title='Foo.Bar.S01E02.XViD-FlexGet'), \
            'Foo.Bar.S01E02.XViD-FlexGet should not have been accepted (exists)'
        assert self.feed.find_entry('accepted', title='Foo.Bar.S01E03.XViD-FlexGet'), \
            'Foo.Bar.S01E03.XViD-FlexGet should have been accepted'
            
    def test_diff_qualities(self):
        self.execute_feed('test_diff_qualities')
        assert self.feed.find_entry('accepted', title='Asdf.S01E02.720p-FlexGet'), \
            'Asdf.S01E02.720p-FlexGet should have been accepted'
