name: Bug report
description: Create a report to help us improve
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug!
  - type: checkboxes
    attributes:
      label: "I've found a bug, and:"
      description: |
        Make sure that your request fulfills all of the following requirements.
      options:
        - label: I've read the [issue guidelines](https://github.com/Flexget/Flexget/blob/develop/.github/CONTRIBUTING.md#issues).
          required: true
        - label: I’m already on the latest version and aware that I should check the [upgrade actions](https://flexget.com/UpgradeActions) after updating to a major or minor version.
          required: true
  - type: textarea
    attributes:
      label: Summary
      description: >
        A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal reproducible config
      description: |
        Paste minimal reproducible config and make sure to redact any personal information (passwords, api keys, etc)
      render: yaml
  - type: textarea
    attributes:
      label: Log
      placeholder: |
        paste the debug-level log output here
      render: text
  - type: textarea
    attributes:
      label: Additional information
      value: |
        **FlexGet version: **
        **Python version: **
        **Installation method: **
        **Using daemon (yes/no): **
        **OS and version: **
        **Link to crash log: **
