name: Bug report
description: Report an unexpected problem or behavior
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        **Before You Start...**

        - Read the [issue guidelines](https://github.com/Flexget/Flexget/blob/develop/.github/CONTRIBUTING.md#issues)
        - Check if there is already an issue about the problem
        - Be aware that you should check the [upgrade actions](https://flexget.com/UpgradeActions) after updating to a major or minor version
  - type: textarea
    attributes:
      label: Summary
      description: >
        Provide a clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal reproducible config
      description: |
        Paste minimal reproducible config and make sure to redact any personal information (passwords, api keys, etc)
      render: yaml
  - type: textarea
    attributes:
      label: Log
      placeholder: |
        paste the debug-level log output here
      render: text
  - type: textarea
    attributes:
      label: Additional information
      value: |
        **FlexGet Version: **
        **Python Version: **
        **OS Version: **
        **Installation Method: **
        **Using Daemon (yes/no): **
