name: Feature request
description: Suggest a request, idea, or new functionality
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        **Before You Start...**

        - Read the [issue guidelines](https://github.com/Flexget/Flexget/blob/develop/.github/CONTRIBUTING.md#issues)
        - Check if there is already an issue about the feature request
  - type: textarea
    attributes:
      label: Summary
      description: >
        Describe the feature you'd like.
    validations:
      required: true
