name: Task
description: Describe a specific piece of work
type: Task
body:
  - type: markdown
    attributes:
      value: |
        **Before You Start...**

        - Read the [issue guidelines](https://github.com/Flexget/Flexget/blob/develop/.github/CONTRIBUTING.md#issues)
        - Check if there is already an issue about the task
  - type: textarea
    attributes:
      label: Summary
      description: >
        Provide a clear and concise description of the task.
    validations:
      required: true
