import re

from guessit.plugins.transformers import Transformer
from guessit.matcher import GuessFinder

main_terms = ['rock', 'punk', 'electro', 'folk', 'grunge', 'country', 'pop', 'club', 'dance', 'house', 'techno', 'metal']


class GuessMusicGenre(Transformer):
    def __init__(self):
        Transformer.__init__(self, 40)

    def supported_properties(self):
        return ['genre']

    def guess_genre(self, string, node=None, options=None):
        # thanks to http://www.musicgenreslist.com/
        register_property('genre', {
            'Art Punk': ['(?i)Art.Punk'],
            # 'Alternative Rock': ['(?i)Alt(ernative.)?Rock'],
            'College Rock': ['(?i)College.Rock'],
            'Experimental Rock': ['(?i)Experimental.Rock'],
            'Gothic Rock': ['(?i)Goth'],
            'Hard Rock': ['(?i)Hard.Rock'],
            'Indie Rock': ['(?i)Indie.Rock'],
            'Progressive Rock': ['(?i)Progressive.Rock'],
            'Electronic Rock': ['(?i)Electronic.Rock'],
            'J-Rock': ['(?i)J-Rock'],
            'Pop/Rock': ['(?i)Pop/Rock'],
            'Soft Rock': ['(?i)Soft.Rock'],
            'Acid Rock': ['(?i)Acid.Rock'],
            'American Trad Rock': ['(?i)American.Trad Rock'],
            'Anatolian Rock': ['(?i)Anatolian.Rock'],
            'Arena Rock': ['(?i)Arena.Rock'],
            'Art Rock': ['(?i)Art.Rock'],
            'Blues-Rock': ['(?i)Blues-Rock'],
            'Glam Rock': ['(?i)Glam.Rock'],
            'Noise Rock': ['(?i)Noise.Rock'],
            # 'Rock & Roll': ['(?i)Rock.{,3}Roll'],
            'Rockabilly': ['(?i)Rockabilly'],
            'Roots Rock': ['(?i)Roots.Rock'],
            'Southern Rock': ['(?i)Southern.Rock'],
            'Time Lord Rock': ['(?i)Time.Lord Rock'],
            'Folk-Rock': ['(?i)Folk-Rock'],
            'Rock': ['(?i)Rock'],
            'Grunge': ['(?i)Grunge'],
            'Hardcore Punk': ['(?i)Hardcore.Punk'],
            'Lo-fi': ['(?i)Lo-fi'],
            'New Wave': ['(?i)New.Wave'],
            'Punk': ['(?i)Punk'],
            'Shoegaze': ['(?i)Shoegaze'],
            'Steampunk': ['(?i)Steampunk'],
            'Acoustic Blues': ['(?i)Acoustic.Blues'],
            'Chicago Blues': ['(?i)Chicago.Blues'],
            'Classic Blues': ['(?i)Classic.Blues'],
            'Contemporary Blues': ['(?i)Contemporary.Blues'],
            'Country Blues': ['(?i)Country.Blues'],
            'Delta Blues': ['(?i)Delta.Blues'],
            'Electric Blues': ['(?i)Electric.Blues'],
            'Lullabies': ['(?i)Lullabies'],
            'Sing-Along': ['(?i)Sing-Along'],
            'Stories': ['(?i)Stories'],
            'Avant-Garde': ['(?i)Avant-Garde'],
            'Baroque': ['(?i)Baroque'],
            'Chamber Music': ['(?i)Chamber.Music'],
            'Chant': ['(?i)Chant'],
            'Choral': ['(?i)Choral'],
            'Classical Crossover': ['(?i)Classical.Crossover'],
            'Early Music': ['(?i)Early.Music'],
            'High Classical': ['(?i)High.Classical'],
            'Impressionist': ['(?i)Impressionist'],
            'Medieval': ['(?i)Medieval'],
            'Minimalism': ['(?i)Minimalism'],
            'Modern Composition': ['(?i)Modern.Composition'],
            'Opera': ['(?i)Opera'],
            'Orchestral': ['(?i)Orchestral'],
            'Renaissance': ['(?i)Renaissance'],
            'Romantic': ['(?i)Romantic'],
            'Wedding Music': ['(?i)Wedding.Music'],
            'Novelty': ['(?i)Novelty'],
            'Standup Comedy': ['(?i)Standup.Comedy'],
            'Vaudeville': ['(?i)Vaudeville'],
            'TV Themes': ['(?i)TV.Themes'],
            'Alternative Country': ['(?i)Alternative.Country'],
            'Americana': ['(?i)Americana'],
            'Bluegrass': ['(?i)Bluegrass'],
            'Contemporary Bluegrass': ['(?i)Contemporary.Bluegrass'],
            'Contemporary Country': ['(?i)Contemporary.Country'],
            'Country Gospel': ['(?i)Country.Gospel'],
            'Country Pop': ['(?i)Country.Pop'],
            'Honky Tonk': ['(?i)Honky.Tonk'],
            'Outlaw Country': ['(?i)Outlaw.Country'],
            'Traditional Bluegrass': ['(?i)Traditional.Bluegrass'],
            'Traditional Country': ['(?i)Traditional.Country'],
            'Urban Cowboy': ['(?i)Urban.Cowboy'],
            'Club / Club Dance': ['(?i)Club'],
            'Breakbeat': ['(?i)Breakbeat'],
            'Brostep': ['(?i)Brostep'],
            'Deep House': ['(?i)Deep.House'],
            'Dubstep': ['(?i)Dubstep'],
            'Electro House': ['(?i)Electro.House'],
            'Exercise': ['(?i)Exercise'],
            'Garage': ['(?i)Garage'],
            'Glitch Hop': ['(?i)Glitch.Hop'],
            'Hardcore': ['(?i)Hardcore'],
            'Hard Dance': ['(?i)Hard.Dance'],
            'Eurodance': ['(?i)Eurodance'],
            'House': ['(?i)House'],
            'Jackin House': ['(?i)Jackin.House'],
            # 'Drum\'n\'bass': ['(?i)Drum.?.?.?bass'],
            'Regstep': ['(?i)Regstep'],
            'Techno': ['(?i)Techno'],
            'Trance': ['(?i)Trance'],
            'Trap': ['Trap'],
            'Bop': ['(?i)Bop'],
            'Lounge': ['(?i)Lounge'],
            'Swing': ['(?i)Swing'],
            '8bit': ['(?i)8-?bit', 'Bitpop', 'Chiptune'],
            'Ambient': ['(?i)Ambient'],
            'Bassline': ['(?i)Bassline'],
            'Crunk': ['(?i)Crunk'],
            'Downtempo': ['(?i)Downtempo'],
            'Electro': ['(?i)Electro'],
            'Electro-swing': ['(?i)Electro-swing'],
            'Electronica': ['(?i)Electronica'],
            'Hardstyle': ['(?i)Hardstyle'],
            'Experimental': ['(?i)Experimental'],
            'Industrial': ['(?i)Industrial'],
            'Trip Hop': ['(?i)Trip.Hop'],
            'Alternative Rap': ['(?i)Alternative.Rap'],
            'Bounce': ['(?i)Bounce'],
            'Dirty South': ['(?i)Dirty.South'],
            'East Coast Rap': ['(?i)East.Coast Rap'],
            'Gangsta Rap': ['(?i)Gangsta.Rap'],
            'Hardcore Rap': ['(?i)Hardcore.Rap'],
            'Hip-Hop': ['(?i)Hip-Hop'],
            'Latin Rap': ['(?i)Latin.Rap'],
            'Old School Rap': ['(?i)Old.School Rap'],
            'Rap': ['(?i)Rap'],
            'Turntablism': ['(?i)Turntablism'],
            'Underground Rap': ['(?i)Underground.Rap'],
            'West Coast Rap': ['(?i)West.Coast Rap'],
            'Chanukah': ['(?i)Chanukah'],
            'Christian': ['(?i)Christian'],
            'Gospel': ['(?i)Gospel'],
            'Qawwali': ['(?i)Qawwali'],
            'March': ['(?i)March'],
            'J-Synth': ['(?i)J-Synth'],
            'J-Ska': ['(?i)J-Ska'],
            'J-Punk': ['(?i)J-Punk'],
            'Jazz': ['(?i)Jazz'],
            'Bebop': ['(?i)Bebop'],
            'Big Band': ['(?i)Big.Band'],
            'Blue Note': ['(?i)Blue.Note'],
            'Cool': ['(?i)Cool'],
            'Dixieland': ['(?i)Dixieland'],
            'Fusion': ['(?i)Fusion'],
            'Hard Bop': ['(?i)Hard.Bop'],
            'Ragtime': ['(?i)Ragtime'],
            'Argentine tango': ['(?i)Argentine.tango'],
            'Baladas y Boleros': ['(?i)Boleros'],
            'Bossa Nova': ['(?i)Bossa.Nova'],
            'Latin': ['(?i)Latin'],
            'Flamenco / Spanish Flamenco': ['(?i)Flamenco'],
            'Portuguese fado': ['(?i)Portuguese.fado'],
            'Reggaeton': ['(?i)Reggaeton'],
            'Environmental': ['(?i)Environmental'],
            'Healing': ['(?i)Healing'],
            'Meditation': ['(?i)Meditation'],
            'Nature': ['(?i)Nature'],
            'Relaxation': ['(?i)Relaxation'],
            'Travel': ['(?i)Travel'],
            'Britpop': ['(?i)Britpop'],
            'Bubblegum Pop': ['(?i)Bubblegum.Pop'],
            'Chamber Pop': ['(?i)Chamber.Pop'],
            'Dance Pop': ['(?i)Dance.Pop'],
            'Dream Pop': ['(?i)Dream.Pop'],
            'Electro Pop': ['(?i)Electro.Pop'],
            'Orchestral Pop': ['(?i)Orchestral.Pop'],
            'Power Pop': ['(?i)Power.Pop'],
            'Synthpop': ['(?i)Synthpop'],
            'Teen Pop': ['(?i)Teen.Pop'],
            'Contemporary R&B': ['(?i)Contemporary.R&B'],
            'Disco': ['(?i)Disco'],
            'Doo Wop': ['(?i)Doo.Wop'],
            'Funk': ['(?i)GFunk', '(?i)Funk'],
            'Modern Soul': ['(?i)Modern.Soul'],
            'Motown': ['(?i)Motown'],
            'Neo-Soul': ['(?i)Neo-Soul'],
            'Northern Soul': ['(?i)Northern.Soul'],
            'Psychedelic Soul': ['(?i)Psychedelic.Soul'],
            'Quiet Storm': ['(?i)Quiet.Storm'],
            'Soul': ['(?i)Soul'],
            'Soul Blues': ['(?i)Soul.Blues'],
            'Southern Soul': ['(?i)Southern.Soul'],
            'Dancehall': ['(?i)Dancehall'],
            'Dub': ['(?i)Dub'],
            'Reggae': ['(?i)Reggae'],
            'Roots Reggae': ['(?i)Roots.Reggae'],
            'Ska': ['(?i)Ska'],
            'Afro Punk': ['(?i)Afro.Punk'],
            'British Invasion': ['(?i)British.Invasion'],
            'Death Metal / Black Metal': ['(?i)(?:Death|Black).Metal'],
            'Gothic Metal': ['(?i)Gothic.Metal'],
            'Hair Metal': ['(?i)Hair.Metal'],
            'Metal': ['(?i)Metal'],
            'Jam Bands': ['(?i)Jam.Bands'],
            'Post Punk': ['(?i)Post.Punk'],
            'Psychedelic': ['(?i)Psychedelic'],
            'Singer/Songwriter': ['(?i)Songwriter'],
            'Surf': ['(?i)Surf'],
            'Alternative Folk': ['(?i)Alternative.Folk'],
            'Contemporary Folk': ['(?i)Contemporary.Folk'],
            'Songwriter': ['(?i)Songwriter'],
            'Indie Folk': ['(?i)Indie.Folk'],
            'Love Song': ['(?i)Love.Song'],
            'New Acoustic': ['(?i)New.Acoustic'],
            'Traditional Folk': ['(?i)Traditional.Folk'],
            'Foreign Cinema': ['(?i)Foreign.Cinema'],
            'Musicals': ['(?i)Musicals'],
            'Original Score': ['(?i)Original.Score'],
            'Soundtrack': ['(?i)Soundtrack'],
            'TV Soundtrack': ['(?i)TV.Soundtrack'],
            'Chicano': ['(?i)Chicano'],
            'Classic': ['(?i)Classic'],
            'Conjunto': ['(?i)Conjunto'],
            'New Mex': ['(?i)New.Mex'],
            'Tex-Mex': ['(?i)Tex-Mex'],
            'A cappella': ['(?i)cappella'],
            'Barbershop': ['(?i)Barbershop'],
            'Doo-wop': ['(?i)Doo-wop'],
            'Gregorian Chant': ['(?i)Gregorian.Chant'],
            'Standards': ['(?i)Standards'],
            'Traditional Pop': ['(?i)Traditional.Pop'],
            'Vocal Pop': ['(?i)Vocal.Pop'],
            'Africa': ['(?i)Africa'],
            'Afro-Beat': ['(?i)Afro-Beat'],
            'Afro-Pop': ['(?i)Afro-Pop'],
            'Asia': ['(?i)Asia'],
            'Australia': ['(?i)Australia'],
            'Cajun': ['(?i)Cajun'],
            'Calypso': ['(?i)Calypso'],
            'Caribbean': ['(?i)Caribbean'],
            'Celtic': ['(?i)Celtic'],
            'Celtic Folk': ['(?i)Celtic.Folk'],
            'Contemporary Celtic': ['(?i)Contemporary.Celtic'],
            'Dangdut': ['(?i)Dangdut'],
            'Drinking Songs': ['(?i)Drinking.Songs'],
            'Drone': ['(?i)Drone'],
            'Europe': ['(?i)Europe'],
            'France': ['(?i)France'],
            'Hawaii': ['(?i)Hawaii'],
            'Indian Ghazal': ['(?i)Indian.Ghazal'],
            'Indian Pop': ['(?i)Indian.Pop'],
            'Japan': ['(?i)Japan'],
            'Japanese Pop': ['(?i)Japanese.Pop'],
            'Klezmer': ['(?i)Klezmer'],
            'Middle East': ['(?i)Middle.East'],
            'North America': ['(?i)North.America'],
            'Ode': ['(?i)Ode'],
            'Polka': ['(?i)Polka'],
            'Soca': ['(?i)Soca'],
            'South Africa': ['(?i)South.Africa'],
            'South America': ['(?i)South.America'],
            'Traditional Celtic': ['(?i)Traditional.Celtic'],
            'Worldbeat': ['(?i)Worldbeat'],
            'Zydeco': ['(?i)Zydeco']
        })
        return None, None

    def second_pass_options(self, mtree, options=None):
        nodes = list(mtree.leaves_containing('genre'))
        if len(nodes) > 1:
            return {'skip_nodes': nodes[:len(nodes) - 1]}
        return None

    def process(self, mtree, options=None):
        GuessFinder(self.guess_genre, 1.0, self.log, options).process_nodes(mtree.unidentified_leaves())
