name: Changelog Update

on:
  push:
    branches:
      - develop

permissions: {}

jobs:
  update-changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.13' # renovate: datasource=python-version depName=python
      UV_VERSION: 0.12.1 # renovate: datasource=pypi depName=uv
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Checkout wiki repo
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          repository: Flexget/wiki
          path: wiki
          token: ${{ secrets.flexgetbot_pat }}
          persist-credentials: true
          ref: main
      - name: Setup Git User
        run: |
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
      - name: Install uv and Python
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          version: ${{ env.UV_VERSION }}
      - name: Update the Changelog
        run: |
          set -x
          uv run scripts/update_changelog.py wiki/ChangeLog.md
          cd wiki
          git add ChangeLog.md
          if ! git diff --cached --exit-code; then
              git commit -m "Automated ChangeLog update"
              git push origin main
          fi
