name: Label PRs
on:
  pull_request_target:
permissions: {}
concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.number || github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  trigger-autofix:
    name: Trigger pre-commit.ci autofix
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # for labeling PRs
    steps:
      - name: Apply the label "pre-commit.ci autofix"
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        with:
          script: |
            const { data } = await github.rest.pulls.listCommits({
              ...context.repo,
              pull_number: context.issue.number
            });
            if (data.at(-1).author.node_id === 'BOT_kgDOBtghQg')
              await github.rest.issues.addLabels({
                ...context.repo,
                issue_number: context.issue.number,
                labels: ['pre-commit.ci autofix'],
              });
