name: Build and release to PyPI and GitHub
on:
  schedule:
    - cron: 0 15 * * *
  workflow_dispatch:
permissions: {}
jobs:
  check:
    name: Check release prerequisites
    runs-on: ubuntu-latest
    outputs:
      new_commits: ${{steps.check.outputs.new_commits}}
    concurrency:
      group: 'check release prerequisites, ${{ github.ref }}'
      cancel-in-progress: true
    steps:
      - name: Check release prerequisites
        id: check
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: |
            if (context.ref !== 'refs/heads/develop')
              core.setFailed("Release script should be run from develop branch.");
            const release = await github.rest.repos.getLatestRelease(context.repo).catch(() => null);
            if (!release) {
              core.info("No release exists, or the latest release has been deleted. Assuming new commits exist.");
              core.setOutput('new_commits', 'true');
              return;
            }
            const { data: diff } = await github.rest.repos.compareCommitsWithBasehead({
              ...context.repo,
              basehead: `${release.data.tag_name}...${context.ref}`,
            });
            core.info(`${context.ref} is ${diff.ahead_by} commits ahead of and ${diff.behind_by} commits behind ${release.data.tag_name}.`);
            core.setOutput('new_commits', diff.ahead_by > 1 || diff.behind_by > 0);
  release:
    name: Build and release
    permissions:
      contents: write # for writing "flexget/_version.py" and release
    runs-on: ubuntu-latest
    if: needs.check.outputs.new_commits == 'true'
    needs: check
    environment: production
    env:
      PYTHON_VERSION: '3.13' # renovate: datasource=python-version depName=python
      UV_VERSION: 0.9.16 # renovate: datasource=pypi depName=uv
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          token: ${{ secrets.flexgetbot_pat }}
          persist-credentials: true
          fetch-depth: 0
      - name: Check Commit Status # Currently, the GitHub frontend private API is being used, which may change at any time. Using the public API, however, is quite complex, as it requires querying both "Get the combined status for a specific reference" and "List check runs for a Git reference", and ensuring that both are 'success'.
        run: |
          commit_state=$(curl -sf -H 'Accept: application/json' 'https://github.com/${{ github.repository }}/commits/deferred_commit_data/${{ github.ref_name }}' | jq -r --arg commit_id "$(git rev-parse HEAD)" '.deferredCommits[] | select(.oid == $commit_id) | .statusCheckStatus.state // "not_found"')
          if [[ "$commit_state" != "success" ]]; then
            echo "::error::Status is '$commit_state'."
            exit 1
          fi
      - name: Install uv and Python
        uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          version: ${{ env.UV_VERSION }}
      - name: Run release script
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.pypi_token }}
        run: scripts/release.sh
      - name: Create GitHub Release
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1
        with:
          tag: ${{ env.RELEASE_TAG }}
          artifacts: dist/*,flexget-config.schema.json
          body: ${{ env.CHANGELOG_BODY }}
