name: Build and release to PyPI
on:
  schedule:
    - cron: 0 15 * * *
  workflow_dispatch: {}
permissions: {}
jobs:
  release:
    permissions:
      actions: write # for cancel workflow runs
      contents: write # for release
      deployments: write # to create a deployment
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.13' # renovate: datasource=python-version depName=python
      UV_VERSION: 0.9.8 # renovate: datasource=pypi depName=uv
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          token: ${{ secrets.flexgetbot_pat }}
          persist-credentials: true
          fetch-depth: 0
      - name: Error if running on a branch other than develop
        run: |
          if [ "$(git rev-parse HEAD)" != "$(git rev-parse origin/develop)" ]; then
            echo "Release script should be run from develop branch."
            exit 1
          fi
      - name: Cancel workflow run if there are no new commits
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: |
            const { execSync } = require('child_process');
            const hasTag = ref => !!execSync(`git tag --points-at ${ref}`).toString();
            if (hasTag('HEAD') || hasTag('HEAD~1')) {
              core.info("No new commits, skipping release");
              await github.rest.actions.cancelWorkflowRun({
                ...context.repo,
                run_id: context.runId
              });
              await new Promise(r => setTimeout(r, 60000));
              core.setFailed("Failed to cancel the workflow run; forcibly terminated.");
            }
      - name: Create Deployment
        id: create-deployment
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: |
            let res = await github.rest.repos.createDeployment({
              ...context.repo,
              ref: context.ref.slice(11),
              required_contexts: []
            });
            core.setOutput('deployment_id', res.data.id);
      - name: Set Deployment Status in_progress
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
                ...context.repo,
                deployment_id: ${{steps.create-deployment.outputs.deployment_id}},
                log_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}/job/${{job.check_run_id}}`,
                state: 'in_progress',
            })
      - name: Check Commit Status
        run: |
          commit_state=$(curl -sf -H 'Accept: application/json' 'https://github.com/${{ github.repository }}/commits/deferred_commit_data/${{ github.ref_name }}' | jq -r --arg commit_id "$(git rev-parse HEAD)" '.deferredCommits[] | select(.oid == $commit_id) | .statusCheckStatus.state // "not_found"')
          if [[ "$commit_state" != "success" ]]; then
            echo "::error::Status is '$commit_state'."
            exit 1
          fi
      - name: Install uv and Python
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          version: ${{ env.UV_VERSION }}
      - name: Run release script
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.pypi_token }}
        run: scripts/release.sh
      - name: Create GitHub Release
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1
        with:
          tag: ${{ env.RELEASE_TAG }}
          artifacts: dist/*,flexget-config.schema.json
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ env.CHANGELOG_BODY }}
      - name: Set Deployment Status Success
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
                ...context.repo,
                deployment_id: ${{steps.create-deployment.outputs.deployment_id}},
                log_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}/job/${{job.check_run_id}}`,
                state: 'success',
            })
      - name: Set Deployment Status Failure
        if: failure()
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
                ...context.repo,
                deployment_id: ${{steps.create-deployment.outputs.deployment_id}},
                log_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}/job/${{job.check_run_id}}`,
                state: 'error',
            })
