name: Build and release to PyPI and GitHub
on:
  schedule:
    - cron: 0 15 * * *
  workflow_dispatch:
permissions: {}
jobs:
  check:
    name: Check release prerequisites
    runs-on: ubuntu-latest
    outputs:
      new_commits: ${{steps.check.outputs.new_commits}}
    concurrency:
      group: 'check release prerequisites, ${{ github.ref }}'
      cancel-in-progress: true
    steps:
      - name: Check release prerequisites
        id: check
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        with:
          script: |
            if (context.ref !== 'refs/heads/develop')
              core.setFailed("Release script should be run from develop branch.");
            const release = await github.rest.repos.getLatestRelease(context.repo).catch(() => null);
            if (!release) {
              core.info("No release exists, or the latest release has been deleted. Assuming new commits exist.");
              core.setOutput('new_commits', 'true');
              return;
            }
            const { data: diff } = await github.rest.repos.compareCommitsWithBasehead({
              ...context.repo,
              basehead: `${release.data.tag_name}...${context.ref}`,
            });
            core.info(`${context.ref} is ${diff.ahead_by} commits ahead of and ${diff.behind_by} commits behind ${release.data.tag_name}.`);
            core.setOutput('new_commits', diff.ahead_by > 1 || diff.behind_by > 0);
  release:
    name: Build and release
    permissions:
      contents: write # for writing "flexget/_version.py" and release
    runs-on: ubuntu-latest
    if: needs.check.outputs.new_commits == 'true'
    needs: check
    environment: production
    env:
      PYTHON_VERSION: '3.13' # renovate: datasource=python-version depName=python
      UV_VERSION: 0.11.8 # renovate: datasource=pypi depName=uv
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ secrets.flexgetbot_pat }}
          persist-credentials: true
          fetch-depth: 0
      - name: Install uv and Python
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          version: ${{ env.UV_VERSION }}
      - name: Run release script
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.pypi_token }}
        run: scripts/release.sh
      - name: Create GitHub Release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1
        with:
          tag: ${{ env.RELEASE_TAG }}
          artifacts: dist/*,flexget-config.schema.json
          body: ${{ env.CHANGELOG_BODY }}
