name: GitHub Actions security analysis with zizmor
on:
  push:
    branches: [develop]
    paths: [.github/workflows/*]
  pull_request:
    paths: [.github/workflows/*]
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  zizmor:
    name: Run zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    env:
      UV_VERSION: 0.8.22 # renovate: datasource=pypi depName=uv
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4 # v6
        with:
          version: ${{ env.UV_VERSION }}
      - name: Run zizmor
        run: uvx zizmor -p --format sarif . > results.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@3599b3baa15b485a2e49ef411a7a4bb2452e7f93 # v3
        with:
          sarif_file: results.sarif
          category: zizmor
