name: GitHub Actions security analysis with zizmor
on:
  push:
    branches: [develop]
    paths: [.github/workflows/*]
  pull_request:
    paths: [.github/workflows/*]
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  zizmor:
    name: Run zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    env:
      UV_VERSION: 0.9.7 # renovate: datasource=pypi depName=uv
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6
        with:
          version: ${{ env.UV_VERSION }}
      - name: Run zizmor
        run: uvx zizmor -p --format sarif . > results.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@5d5cd550d3e189c569da8f16ea8de2d821c9bf7a # v3
        with:
          sarif_file: results.sarif
          category: zizmor
