name: GitHub Actions security analysis with zizmor
on:
  push:
    branches: [develop]
    paths: [.github/workflows]
  pull_request:
    paths: [.github/workflows]
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  zizmor:
    name: Run zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    env:
      UV_VERSION: 0.8.4 # renovate: datasource=pypi depName=uv
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6
        with:
          enable-cache: true
          version: ${{ env.UV_VERSION }}
      - name: Run zizmor
        run: uvx zizmor -p --format sarif . > results.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@51f77329afa6477de8c49fc9c7046c15b9a4e79d # v3
        with:
          sarif_file: results.sarif
          category: zizmor
