name: GitHub Actions security analysis with zizmor
on:
  push:
    branches: [develop]
    paths: &paths [.github/workflows/*]
  pull_request:
    paths: *paths
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  zizmor:
    name: Run zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    env:
      UV_VERSION: 0.11.29 # renovate: datasource=pypi depName=uv
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          version: ${{ env.UV_VERSION }}
      - name: Run zizmor
        run: uvx zizmor -p --format sarif . > results.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@7188fc363630916deb702c7fdcf4e481b751f97a # v4
        with:
          sarif_file: results.sarif
          category: zizmor
